export let countryCode = [
    ["France", "BWRBWRBWR"],
    ["netherland", "RRRWWWBBB"],
    ["Russia", "WWWBBBRRR"],
    ["Italy", "GWRGWRGWR"],
    ["Ireland", "GWOGWOGWO"],
    ["Romania", "BYRBYRBYR"],
    ["Ivory Coast", "OWGOWGOWG"],
    ["Chad", "BYRBYRBYR"],
    ["Guinea", "RYGRYGRYG"],
    ["Mali", "GYRGYRGYR"],
    ["Niger", "OOOWOWGGG"],
    ["Nigeria", "GWGGWGGWG"],
    ["Bulgaria", "WWWGGGRRR"],
    ["Luxembourg", "RRRWWWBBB"],
    ["Armenia", "RRRBBBOOO"],
    ["Latvia", "RRRWWWRRR"],
    ["India", "OOOWWWGGG"],
    ["Iran", "GGGWWWRRR"],
    ["Andorra", "BYRBYRBYR"],
    ["Austria", "RRRWWWRRR"],
    ["Bolivia", "RRRYYYGGG"],
    ["Cameroon", "GYRGYRGYR"],
    ["Colombia", "YYYBBBRRR"],
    ["Croatia", "RRRWWWBBB"],
    ["Dominican Republic", "BWRWWWRWB"],
    ["Ecuador", "YYYBBBRRR"],
    ["El Salvador", "BBBWWWBBB"],
    ["Equatorial Guinea", "GGGBWWRRR"],
    ["Finland", "WBWBBBWBW"],
    ["Gabon", "RRRYYYBBB"],
    ["Ghana", "RRRYYYGGG"],
    ["Hungary", "RRRWWWGGG"],
    ["Kazakhstan", "BBBBYBBBB"],
    ["Lebanon", "RRRWGWRRR"],
    ["Lithuania", "YYYGGGRRR"],
    ["Mexico", "GWRGWRGWR"],
    ["Moldova", "BYRBYRBYR"],
    ["Myanmar", "YYYGWGRRR"],
    ["Pakistan", "WGGWGGWGG"],
    ["Paraguay", "RRRWWWBBB"],
    ["Peru", "RWRRWRRWR"],
    ["Rwanda", "BBBYYYRRR"],
    ["Senegal", "GYRGYRGYR"],
    ["Serbia", "RRRBBBWWW"],
    ["Sierra Leone", "GGGWWWBBB"],
    ["Slovakia", "WWWBBBRRR"],
    ["Slovenia", "WWWBBBRRR"],
    ["Tajikistan", "RRRWWWGGG"],
    ["Tunisia", "RRRRWRRRR"],
    ["Venezuela", "YYYBBBRRR"],
    ["Vietnam", "RRRRYRRRR"],
];
